#!/usr/bin/env bash
# Bootstrap per-module README.md stubs.
# CI (docs.yml) regenerates these on every push via terraform-docs.
# This script just creates an initial pass so the repo isn't empty before CI runs.

set -euo pipefail
cd "$(dirname "$0")/.."

for d in modules/*/; do
  name=$(basename "$d")
  [ "$name" = "_template" ] && continue
  out="$d/README.md"

  cat > "$out" <<EOF
# $name

Reusable Terraform module: \`$name\`.

> **This README is regenerated by terraform-docs in CI on every push to main.**
> See \`.github/workflows/docs.yml\`. To preview locally:
>     ./scripts/generate-module-docs.sh

## Usage

\`\`\`hcl
module "$name" {
  source = "../../modules/$name"
  # See variables.tf for required inputs.
}
\`\`\`

<!-- BEGIN_TF_DOCS -->
<!-- Generated by terraform-docs - do not edit between these markers -->
<!-- END_TF_DOCS -->
EOF

  echo "wrote $out"
done
